# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  image: latest
  # see issue below - needs newer image
  # os: ubuntu-22.04
  tools:
    python: "3.9"
    nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  jobs:
    # from https://github.com/remotestorage/remotestorage.js/issues/1268
    post_install:
      - npm install -g jsdoc   

# Build documentation in the docs/ directory with Sphinx
# sphinx:
#    configuration: docs/conf.py

sphinx:
   configuration: source/conf.py

formats:
   - pdf

# Python requirements required to build docs
python:
   version: 3.8
   install:
   - requirements: requirements.txt

