# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    nodejs: "16"
  jobs:
    post_install:
      - npm install -g jsdoc

sphinx:
   configuration: source/conf.py

formats:
   - pdf

# Python requirements required to build docs
python:
   install:
   - requirements: requirements.txt

# per chatgpt :-) this should be run to try to fix footnotes
# ... chatgtp is wrong, so putting this on TODO
# build:
#   # this should be triggered by the "-e" ... supposedly
#   script:
#     - sphinx-build -M latex souurce build/latex
#     - latexmk -pdf -cd -use-make -interaction=nonstopmode build/latex/*.tex
#     - latexmk -pdf -cd -use-make -interaction=nonstopmode build/latex/*.tex
